-- CreateTable
CREATE TABLE "USER" (
    "USER_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "USER_DATA" TEXT NOT NULL,
    "USER_SALT" TEXT NOT NULL,
    "USER_DATECREATED" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_DATEUPDATED" DATETIME NOT NULL,
    "USER_PICTURE" BLOB
);

-- CreateTable
CREATE TABLE "CREDENTIAL" (
    "CREDENTIAL_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CREDENTIAL_SERVICENAME" TEXT NOT NULL,
    "CREDENTIAL_TITLE" TEXT NOT NULL,
    "CREDENTIAL_DATA" TEXT NOT NULL,
    "CREDENTIAL_URL" TEXT,
    "CREDENTIAL_ISWEAK" BOOLEAN NOT NULL,
    "CREDENTIAL_DATECREATED" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREDENTIAL_DATEUPDATED" DATETIME NOT NULL,
    "CREDENTIAL_SERVICETYPE" TEXT NOT NULL DEFAULT 'Personal',
    "CREDENTIAL_PICTURE" BLOB,
    "CREDENTIAL_ISFAVOURITE" BOOLEAN NOT NULL DEFAULT false,
    "USER_ID" INTEGER NOT NULL,
    CONSTRAINT "CREDENTIAL_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SECURITYQUESTION" (
    "SECURITYQUESTION_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SECURITYQUESTION_DATA" TEXT NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    CONSTRAINT "SECURITYQUESTION_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TRASH" (
    "TRASH_ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TRASH_DATETEMPDELETED" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREDENTIAL_ID" INTEGER NOT NULL,
    CONSTRAINT "TRASH_CREDENTIAL_ID_fkey" FOREIGN KEY ("CREDENTIAL_ID") REFERENCES "CREDENTIAL" ("CREDENTIAL_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_USER_DATA_key" ON "USER"("USER_DATA");

-- CreateIndex
CREATE UNIQUE INDEX "SECURITYQUESTION_USER_ID_key" ON "SECURITYQUESTION"("USER_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TRASH_CREDENTIAL_ID_key" ON "TRASH"("CREDENTIAL_ID");
